### ISSUE TITLE
[FEATURE] Adjust the speed and Import the GIFs

### ISSUE THREAD

**Issue by khangtrn96** [dylandev125/nft-gif-generator#2]
I have ideas for 2 features:
1. Adjust the speed for each frame.
or
2. Import the GIFs (edited from photoshop) in the project. After that, combine the GIFs and images together, and export the GIFs in output file.
Thanks so much !

**Comment by jusdy** [comment]
you should take a look at "createGif" function
============
encoder.setDelay(150) // Set the delay time of the gif
============

you can set the delay of the frames yourself using the function above :)

in case of second, i didn't think about combining gifs and images, will find a solution

**Comment by khangtrn96** [comment]
In case of second, I have found a project can combine GIFs together. I don't know C++ language, so I don't know how to run it. [https://github.com/Goldo02/gif_art_engine_for_nft.git](url).
