### ISSUE TITLE
[Feature] Add more types of layers

### ISSUE THREAD

**Issue by khangtrn96** [dylandev125/nft-gif-generator#3]
I see the project has 5 types of layers available. I want to add more types of layers, what should I do? For example I want to add background type. If I want the background to be a static image (when exporting) then I have to create 8 static images for the background, right?

**Comment by jusdy** [comment]
correct
you should add background attr in the layer folder with 8 frame images each

**Comment by khangtrn96** [comment]
I see the project has 5 types of layers available. I want to add more types of layers, what should I do? For example, I want to add background type.
