### ISSUE TITLE
[ERROR] Overlay between layers.

### ISSUE THREAD

**Issue by khangtrn96** [dylandev125/nft-gif-generator#4]
I have edited on config.js file like this, but some GIFs have overlaid between layers. How can I fix it ? Thanks !

`const layersOrder = [
    {
        name: 'body',
        number: {
            common:   3,
            uncommon: 1,
            rare:     0,
            epic:     0,
        }
    },
    {
        name: 'ears',
        number: {
            common:   6,
            uncommon: 2,
            rare:     0,
            epic:     0,
        }
    },

    {
        name: 'skin',
        number: {
            common:   5,
            uncommon: 2,
            rare:     0,
            epic:     0,
        }
    },
    {
        name: 'eyes',
        number: {
            common:   0,
            uncommon: 2,
            rare:     0,
            epic:     0,
        }
    },
    {
        name: 'accessories',
        number: {
            common:   0,
            uncommon: 1,
            rare:     0,
            epic:     0,
        }
    },`

**Comment by jusdy** [comment]
It should depend on layer images, you should try with other images in layer
