### ISSUE TITLE
[FEATURE] Rename folder.

### ISSUE THREAD

**Issue by khangtrn96** [dylandev125/nft-gif-generator#5]
I see the folder structure is "layers/body/common/1/images". Can I rename "1" folder to become "Green" folder? For example, "layers/body/common/Green/images".

**Comment by jusdy** [comment]
yes, you can
it depends on your decision
just customize the code as you want

**Comment by khangtrn96** [comment]
But initialy, your code is used to identify the folder as a number, right? if I rename “numbers” folder to become “text” folder, I have to fix a lot of places so that the code recognize the “text” . Can you tell me where I need to config? Thanks a lot !

**Comment by jusdy** [comment]
please just take a look at "saveLayer" function
you can see the progress of making the result folder
and also you should need to fix "createGif" function for fixing gif saving folder name.

**Comment by dylandev125** [comment]
completed
